<?php

/**
 * Created by Jorge P. Hernandez Lalcebo
 * Mail: lalcebo2003@gmail.com
 * Date: 3/28/21 11:40 PM
 */

declare(strict_types=1);

namespace Lalcebo\Aws\Params\Athena\Actions;

use Lalcebo\Aws\Params\Parameter;

/**
 * Lists available workgroups for the account.
 *
 * @package Lalcebo\Aws\Params\Athena\Actions
 * @see https://docs.aws.amazon.com/athena/latest/APIReference/API_ListWorkGroups.html
 */
class ListWorkGroups extends Parameter
{
    /**
     * The maximum number of workgroups to return in this request.
     *
     * @var int
     */
    public $maxResults;

    /**
     * A token generated by the Athena service that specifies where to continue pagination if a previous
     * request was truncated. To obtain the next set of pages, pass in the NextToken from the response
     * object of the previous page call.
     *
     * @var string
     */
    public $nextToken;

    /**
     * Lists available workgroups for the account.
     *
     * @param  int|null  $maxResults The maximum number of workgroups to return in this request.
     * @param  string|null  $nextToken A token generated by the Athena service that specifies where
     * to continue pagination if a previous request was truncated. To obtain the next set of pages,
     * pass in the NextToken from the response object of the previous page call.
     */
    public function __construct(int $maxResults = null, string $nextToken = null)
    {
        $this->maxResults = numericRangeValid($maxResults, 1, 50);
        $this->nextToken = $nextToken;
    }
}
